FAST-gamsungcoding/BE_MiniProject

src/main/java/com/gamsung/backend/domain/member/entity/Member.java, src/main/java/com/gamsung/backend/domain/member/repository/MemberRepository.java
=> Member 엔티티 및 레포지토리 추가

src/main/java/com/gamsung/backend/global/config/SecurityConfig.java, src/main/java/com/gamsung/backend/global/config/SecurityFilterConfig.java
일단 모든 URL을 permitAll로 설정했습니다.
close #9
=> 기본적인 시큐리티 설정과 필터 설정 추가

.env.example, build.gradle, src/main/java/com/gamsung/backend/global/jwt/JwtProvider.java, src/main/java/com/gamsung/backend/global/jwt/dto/JwtPayload.java, src/main/java/com/gamsung/backend/global/jwt/exception/JwtInvalidTokenException.java, src/main/java/com/gamsung/backend/global/jwt/exception/JwtTokenExpiredException.java, src/main/resources/application-dev.yaml, src/main/resources/application-test.yaml, src/main/resources/application.yaml, src/test/java/com/gamsung/backend/global/jwt/JwtProviderTest.java
=> JWT 토큰 발급 클래스 추가

.env.example, build.gradle, docker-compose.yml, src/main/java/com/gamsung/backend/BackendApplication.java, src/main/java/com/gamsung/backend/global/config/RedisConfig.java, src/main/java/com/gamsung/backend/global/jwt/dto/JwtPayload.java, src/main/java/com/gamsung/backend/global/jwt/entity/JwtRedisEntity.java, src/main/java/com/gamsung/backend/global/jwt/repository/JwtRedisRepository.java, src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java, src/main/resources/application.yaml, src/test/java/com/gamsung/backend/global/jwt/JwtProviderTest.java, src/test/java/com/gamsung/backend/global/jwt/service/JwtServiceTest.java
=> jwt 리프레시 토큰 저장을 위한 Redis 추가

src/main/java/com/gamsung/backend/global/jwt/JwtPair.java
=> JwtPair 추가

src/main/java/com/gamsung/backend/global/config/SecurityConfig.java, src/main/java/com/gamsung/backend/global/config/SecurityFilterConfig.java, src/main/java/com/gamsung/backend/global/security/jwt/JwtAuthenticationProvider.java, src/main/java/com/gamsung/backend/global/security/jwt/JwtAuthenticationToken.java, src/main/java/com/gamsung/backend/global/security/jwt/JwtFilter.java
=> JwtFilter 추가

src/main/java/com/gamsung/backend/domain/member/controller/MemberController.java, src/main/java/com/gamsung/backend/domain/member/controller/request/MemberControllerLoginRequest.java, src/main/java/com/gamsung/backend/domain/member/controller/request/MemberControllerRegisterEmailCheckRequest.java, src/main/java/com/gamsung/backend/domain/member/controller/request/MemberControllerRegisterRequest.java, src/main/java/com/gamsung/backend/domain/member/dto/request/MemberLoginRequest.java, src/main/java/com/gamsung/backend/domain/member/dto/request/MemberRegisterRequest.java, src/main/java/com/gamsung/backend/domain/member/dto/response/MemberLoginResponse.java, src/main/java/com/gamsung/backend/domain/member/dto/response/MemberLogoutResponse.java, src/main/java/com/gamsung/backend/domain/member/dto/response/MemberRegisterEmailCheckResponse.java, src/main/java/com/gamsung/backend/domain/member/dto/response/MemberRegisterResponse.java, src/main/java/com/gamsung/backend/domain/member/exception/MemberAlreadyExistedException.java, src/main/java/com/gamsung/backend/domain/member/exception/MemberLoginWrongPasswordException.java, src/main/java/com/gamsung/backend/domain/member/exception/MemberNotFoundException.java, src/main/java/com/gamsung/backend/domain/member/repository/MemberRepository.java, src/main/java/com/gamsung/backend/domain/member/service/MemberService.java, src/main/java/com/gamsung/backend/global/common/ApiResponse.java, src/main/java/com/gamsung/backend/global/jwt/dto/JwtPayload.java, src/test/http/member/login.http, src/test/http/member/logout.http, src/test/http/member/register.http, src/test/http/member/registerEmailCheck.http
=> 멤버 컨트롤러 및 서비스 추가

build.gradle, src/main/java/com/gamsung/backend/BackendApplication.java, src/main/java/com/gamsung/backend/domain/accomodation/controller/AccomodationController.java, src/main/java/com/gamsung/backend/domain/cart/controller/CartController.java, src/main/java/com/gamsung/backend/domain/member/controller/MemberController.java, src/main/java/com/gamsung/backend/domain/orders/controller/OrdersController.java, src/main/java/com/gamsung/backend/global/common/BaseTime.java, src/main/java/com/gamsung/backend/global/config/SwaggerConfig.java, src/main/java/com/gamsung/backend/global/config/SwaggerDescriptionConfig.java
close #23, close #25
-프론트 서버의 테스트를 위해 테스트 return 값 작성
-swagger에 API 설명 작성
=> Feat : Swagger 코드 작성 및 테스트 데이터 작성

src/main/java/com/gamsung/backend/global/config/SecurityConfig.java, src/main/java/com/gamsung/backend/global/config/SecurityFilterConfig.java, src/main/java/com/gamsung/backend/global/jwt/JwtProvider.java, src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java, src/main/java/com/gamsung/backend/global/jwt/controller/request/RefreshAccessTokenRequest.java, src/main/java/com/gamsung/backend/global/jwt/security/JwtAuthenticationProvider.java, src/main/java/com/gamsung/backend/global/jwt/security/JwtAuthenticationToken.java, src/main/java/com/gamsung/backend/global/jwt/security/JwtFilter.java, src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java, src/test/http/member/refresh.http
=> 액세스 토큰 리프레시 API 추가

src/main/java/com/gamsung/backend/domain/accomodation/controller/AccomodationController.java, src/main/java/com/gamsung/backend/domain/member/controller/MemberController.java, src/main/java/com/gamsung/backend/domain/orders/controller/OrdersController.java, src/main/java/com/gamsung/backend/global/common/ControllerResponse.java, src/main/java/com/gamsung/backend/global/config/CorsConfig.java, src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java
=> Cors 세팅 추가

src/main/java/com/gamsung/backend/BackendApplication.java, src/main/java/com/gamsung/backend/domain/member/service/MemberService.java, src/main/java/com/gamsung/backend/global/config/RedisConfig.java, src/main/java/com/gamsung/backend/global/jwt/repository/JwtRedisRepository.java, src/main/java/com/gamsung/backend/global/jwt/repository/RedisRepository.java, src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java, src/test/java/com/gamsung/backend/global/jwt/service/JwtServiceTest.java
=> 레디스 접근을 RestTemplate으로 변경

src/main/java/com/gamsung/backend/global/jwt/repository/JwtRedisRepository.java, src/test/java/com/gamsung/backend/global/jwt/repository/JwtRedisRepositoryTest.java
=> JWT Redis Repository 통합테스트 코드 작성

.github/workflows/CD.yml, .github/workflows/CI.yml, appspec.yml, build.gradle
=> github actions 스크립트 작성

.github/workflows/CD.yml
Motivation:
- 모든 프로젝트 파일들을 저장하도록 수정하려 합니다.
Modification:
- CD.yml 수정
=> Fix: CD.yml 수정

.github/workflows/CD.yml, appspec.yml, scripts/check_server.sh, scripts/move_server_jar.sh, scripts/server_start.sh, scripts/server_stop.sh, src/main/resources/application-prod.yaml
=> 배포 시 발생했던 오류들 수정

src/main/java/com/gamsung/backend/domain/accomodation/controller/AccomodationController.java, src/main/java/com/gamsung/backend/domain/cart/controller/CartController.java, src/main/java/com/gamsung/backend/domain/member/controller/MemberController.java, src/main/java/com/gamsung/backend/domain/orders/controller/OrdersController.java, src/main/java/com/gamsung/backend/global/common/ApiResponse.java, src/main/java/com/gamsung/backend/global/common/BaseException.java, src/main/java/com/gamsung/backend/global/common/BaseTime.java, src/main/java/com/gamsung/backend/global/common/ErrorCode.java, src/main/java/com/gamsung/backend/global/common/GlobalExceptionHandler.java
- ## GlobalExceptionHandler 구축
- 기본으로 뼈대 작성해놨습니다. 
- 발생하는 예외를 잡을때 @ExceptionHandler 안에 발생하는 예외 클래스를 작성해주시면 해당 클래스를 잡습니다.
- 실제 사용하실때는 Controller에서 발생하는 예외만을 잡습니다.
- ## GlobalBaseTime 엔티티 구축
- createdAt,modifiyedAt이 들어가는 컬럼들을 가지고 있는 엔티티입니다.
- 모든 엔티티에 extends 해서 사용해주시면 됩니다.
- @EntityListeners(AuditingEntityListener.class)를 엔티티에 넣어주시면 됩니다.
- ## Global ApiResponse 구축
- 성공,실패에 대한 응답들을 공통화 시킨 클래스를 만들었습니다.
- 예상 응답 
> {       "code" : 5000,
"data" : "유효하지 않은 엑세스 토큰입니다."
}
- ## ErrorCode 생성
-code와 data로 구성된 ENUM 타입이고 실제 에러가 발생할때 해당 부분에 값을 넣어주시면 됩니다.
-예시 
> if (body == null) {
throw new BaseException(ErrorCode.NO_RESULT_SEARCH_LOCATION);
}
close #37
=> Feat : Global로 쓰이는 클래스들 뼈대 구축

src/main/java/com/gamsung/backend/domain/member/controller/MemberController.java, src/main/java/com/gamsung/backend/global/common/GlobalExceptionHandler.java, src/main/java/com/gamsung/backend/global/config/WebMvcConfig.java, src/main/java/com/gamsung/backend/global/resolver/AuthContext.java, src/main/java/com/gamsung/backend/global/resolver/MemberAuth.java, src/main/java/com/gamsung/backend/global/resolver/MemberAuthArgumentResolver.java
=> MemberAuthArgumentResolver 추가

src/main/java/com/gamsung/backend/domain/member/entity/Member.java, src/main/java/com/gamsung/backend/global/common/BaseTime.java
=> BaseTime 수정

src/main/resources/application-prod.yaml
=> 배포 시 ddl-auto 관련 설정 수정

src/main/java/com/gamsung/backend/global/config/SecurityFilterConfig.java, src/test/java/com/gamsung/backend/global/common/BaseIntegrationTest.java, src/test/java/com/gamsung/backend/global/factory/MemberTestFactory.java, src/test/java/com/gamsung/backend/integration/MemberIntegrationTest.java
=> 멤버 관련 API의 통합 테스트 코드 작성

src/main/java/com/gamsung/backend/global/config/SecurityFilterConfig.java
=> Fix: cors preflight 관련 설정 추가

src/main/java/com/gamsung/backend/global/common/ApiResponse.java, src/main/java/com/gamsung/backend/global/exception/GlobalExceptionHandler.java
=> ApiResponse 절충안

src/main/java/com/gamsung/backend/domain/accomodation/controller/AccomodationController.java, src/main/java/com/gamsung/backend/domain/accomodation/dto/response/AccomodationDetailResponse.java, src/main/java/com/gamsung/backend/domain/accomodation/entity/Accomodation.java, src/main/java/com/gamsung/backend/domain/accomodation/exception/AccomodationNotFoundException.java, src/main/java/com/gamsung/backend/domain/accomodation/repository/AccomodationRepository.java, src/main/java/com/gamsung/backend/domain/accomodation/service/AccomodationService.java, src/main/java/com/gamsung/backend/domain/image/exception/ImageNotFoundException.java, src/main/java/com/gamsung/backend/domain/image/repository/ImageRepository.java, src/main/java/com/gamsung/backend/domain/image/service/ImageService.java, src/main/java/com/gamsung/backend/global/common/ApiResponse.java, src/main/java/com/gamsung/backend/global/common/ErrorCode.java, src/main/java/com/gamsung/backend/global/common/GlobalExceptionHandler.java
=> 특정 숙소 조회 기능 구현 

src/main/java/com/gamsung/backend/domain/member/controller/MemberController.java, src/main/java/com/gamsung/backend/global/exception/GlobalExceptionHandler.java, src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java
=> 멤버 도메인 부분을 APIResponse 절충안으로 변경

src/main/java/com/gamsung/backend/domain/member/service/MemberService.java, src/main/java/com/gamsung/backend/global/jwt/JwtProvider.java, src/main/java/com/gamsung/backend/global/jwt/dto/JwtPayload.java, src/main/java/com/gamsung/backend/global/jwt/security/JwtAuthenticationProvider.java, src/main/java/com/gamsung/backend/global/jwt/security/JwtAuthenticationToken.java, src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java, src/main/java/com/gamsung/backend/global/resolver/AuthContext.java, src/main/java/com/gamsung/backend/global/resolver/MemberAuthArgumentResolver.java, src/test/java/com/gamsung/backend/global/jwt/repository/JwtRedisRepositoryTest.java, src/test/java/com/gamsung/backend/global/jwt/service/JwtServiceTest.java
=> JwtPayload에 멤버 ID 추가

src/main/java/com/gamsung/backend/domain/order/controller/OrderController.java, src/main/java/com/gamsung/backend/domain/order/dto/request/OrderAccommodationRequest.java, src/main/java/com/gamsung/backend/domain/order/dto/response/BookDateAvailableResponse.java, src/main/java/com/gamsung/backend/domain/order/dto/response/OrderAccommodationResponse.java, src/main/java/com/gamsung/backend/domain/order/dto/response/OrderResponse.java, src/main/java/com/gamsung/backend/domain/order/dto/response/SoldOutOrder.java, src/main/java/com/gamsung/backend/domain/order/entity/Order.java, src/main/java/com/gamsung/backend/domain/order/exception/BookDateUnavailableException.java, src/main/java/com/gamsung/backend/domain/order/exception/OrderErrorCode.java, src/main/java/com/gamsung/backend/domain/order/exception/OrderExceptionHandler.java, src/main/java/com/gamsung/backend/domain/order/exception/OrderNotFoundException.java, src/main/java/com/gamsung/backend/domain/order/exception/OrderSoldOutException.java, src/main/java/com/gamsung/backend/domain/order/repository/OrderRepository.java, src/main/java/com/gamsung/backend/domain/order/service/OrderService.java
Motivation:
- 다른 도메인에서의 사용을 위해 Order도메인 파일 업로드
Modification:
- Order도메인 개발(미완)
=> Feat: Order 도메인 파일 업로드

src/main/java/com/gamsung/backend/domain/order/controller/OrderController.java, src/main/java/com/gamsung/backend/domain/order/service/OrderService.java
Motivation:
- 빌드 가능하게 에러 수정, 컨트롤러 반환값 수정
Modification:
- OrderController 반환값 ApiResponse사용하게 변경
- 빌드때 에러 뜨는 빨간줄 주석 처리
=> Fix: Order 도메인 에러 수정

src/main/java/com/gamsung/backend/domain/accomodation/controller/AccomodationController.java, src/main/resources/import.sql
=> import.sql 추가

src/main/java/com/gamsung/backend/domain/accommodation/entity/Accommodation.java, src/main/java/com/gamsung/backend/global/openapi/OpenApiService.java
- 검증을 위해 사용했던 contentId 제거
- if 문으로 하나하나 검사하던 로직 -> try-catch로 한번에 처리
=> Accommodation 엔티티 수정 및 검증 if -> try-catch로 변경

src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java, src/main/java/com/gamsung/backend/global/jwt/controller/request/RefreshAccessTokenControllerRequest.java, src/main/java/com/gamsung/backend/global/jwt/controller/request/RefreshAccessTokenRequest.java, src/test/http/member/refresh.http
=> 리프레시 토큰 요청 형식 수정

src/main/java/com/gamsung/backend/global/exception/GlobalExceptionHandler.java
Motivation:
- order handler쪽 수정
Modification:
- 오타 수정
=> Fix: GlobalExceptionHandler 오타 수정

src/main/java/com/gamsung/backend/domain/order/service/OrderService.java
- 숙소 없는경우 예외처리 추가
- 숙소 없는경우 숙소 도메인 쪽에서 exception 터짐
=> Fix: Order 수정 - 숙소 없는경우 예외처리

src/main/java/com/gamsung/backend/domain/order/service/OrderService.java
Motivation:
- 숙소 품절여부 확인 오류 수정
Modification:
- 숙소 품절여부 확인 오류 수정
=> Fix: Order 수정 - 오류 수정

src/main/java/com/gamsung/backend/domain/order/service/OrderService.java
- transactional readonly 추가
- transactional readonly 추가
=> Fix: Order 수정 - transactional readonly 추가

src/main/java/com/gamsung/backend/domain/member/service/MemberService.java, src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java, src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java, src/test/java/com/gamsung/backend/domain/member/controller/MemberControllerTest.java, src/test/java/com/gamsung/backend/domain/member/repository/MemberRepositoryTest.java, src/test/java/com/gamsung/backend/domain/member/service/MemberServiceTest.java, src/test/java/com/gamsung/backend/global/jwt/controller/JwtControllerTest.java, src/test/java/com/gamsung/backend/global/security/WithMockCustomJWTSecurityContextFactory.java, src/test/java/com/gamsung/backend/global/security/WithMockCustomMember.java
=> 멤버 도메인 유닛 테스트 추가

src/main/java/com/gamsung/backend/global/config/SecurityConfig.java, src/main/java/com/gamsung/backend/global/config/SecurityFilterConfig.java, src/main/java/com/gamsung/backend/global/jwt/security/JwtExceptionFilter.java
=> JwtExceptionFilter 추가

src/main/java/com/gamsung/backend/domain/cart/controller/CartController.java, src/main/java/com/gamsung/backend/domain/cart/dto/request/CartDeleteRequest.java, src/main/java/com/gamsung/backend/domain/cart/dto/request/CartEntryRequest.java, src/main/java/com/gamsung/backend/domain/cart/exception/CartException.java, src/main/java/com/gamsung/backend/domain/member/dto/request/MemberLoginRequest.java, src/main/java/com/gamsung/backend/domain/member/dto/request/MemberRegisterRequest.java, src/main/java/com/gamsung/backend/domain/order/dto/request/OrderAccommodationRequest.java, src/main/java/com/gamsung/backend/global/exception/ErrorCode.java, src/main/java/com/gamsung/backend/global/exception/GlobalExceptionHandler.java, src/main/java/com/gamsung/backend/global/exception/ValidationCode.java
- 공통 예외 5003 부분은 @Valid를 통해 걸러지기에 DTO 부분에 예외 메시지를 통해 타입이 안 맞거나 비어있을 시 무조건 5003이 발생하도록 작성
-공통 예외 5002 부분에서 발생할 수 있는 DB Error 부분 잡아서 처리
- 5000,5001번은 JWT Filter에서 처리를 해야하므로 상우님이 진행할 예정
close #114
=> Refactor : 공통 예외 추가

src/main/java/com/gamsung/backend/domain/accommodation/service/AccommodationService.java, src/main/java/com/gamsung/backend/domain/image/entity/Image.java, src/main/java/com/gamsung/backend/domain/image/repository/ImageRepository.java, src/main/java/com/gamsung/backend/domain/image/service/ImageService.java, src/main/java/com/gamsung/backend/global/exception/ErrorCode.java
=> Refactor: Accommodation 내부 로직 변경

http/accommodation/find_accommodation.http, http/accommodation/find_accommodation_list.http, http/cart/cart_delete.http, http/cart/cart_save.http, http/cart/find_cart.http, http/member/log_out.http, http/member/sign_in.http, http/member/sign_up.http, http/order/check_date_available.http, http/order/order.http
- 테스트 HTTP 코드 작성
- 테스트 HTTP 코드 작성
=> Test: 테스트 HTTP 코드 작성

src/main/java/com/gamsung/backend/domain/order/controller/OrderController.java, src/main/java/com/gamsung/backend/domain/order/dto/request/OrderAccommodationRequest.java, src/main/java/com/gamsung/backend/domain/order/repository/OrderRepository.java, src/main/java/com/gamsung/backend/global/exception/ErrorCode.java
Docs: Order description 작성
- Order description 작성
- Order description 작성
=> Docs/order description 작성

src/main/java/com/gamsung/backend/domain/member/controller/MemberController.java, src/main/java/com/gamsung/backend/domain/member/exception/MemberNotFoundException.java, src/main/java/com/gamsung/backend/domain/member/service/MemberService.java, src/main/java/com/gamsung/backend/global/config/SecurityConfig.java, src/main/java/com/gamsung/backend/global/exception/ErrorCode.java, src/main/java/com/gamsung/backend/global/exception/ForbiddenException.java, src/main/java/com/gamsung/backend/global/exception/UnAuthException.java, src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java, src/main/java/com/gamsung/backend/global/jwt/controller/request/RefreshAccessTokenControllerRequest.java, src/main/java/com/gamsung/backend/global/jwt/entity/JwtBlackListRedisEntity.java, src/main/java/com/gamsung/backend/global/jwt/exception/JwtExpiredAccessTokenException.java, src/main/java/com/gamsung/backend/global/jwt/exception/JwtInvalidAccessTokenException.java, src/main/java/com/gamsung/backend/global/jwt/repository/JwtBlackListRedisRepository.java, src/main/java/com/gamsung/backend/global/jwt/security/JwtAuthenticationProvider.java, src/main/java/com/gamsung/backend/global/jwt/security/JwtExceptionFilter.java, src/main/java/com/gamsung/backend/global/jwt/security/JwtFilter.java, src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java, src/main/java/com/gamsung/backend/global/jwt/util/JwtUtil.java, src/test/java/com/gamsung/backend/domain/member/controller/MemberControllerTest.java, src/test/java/com/gamsung/backend/domain/member/service/MemberServiceTest.java, src/test/java/com/gamsung/backend/global/jwt/controller/JwtControllerTest.java, src/test/java/com/gamsung/backend/global/jwt/repository/JwtRedisRepositoryTest.java
=> Jwt 관련 오류 수정 및 기능 추가

src/main/java/com/gamsung/backend/domain/order/controller/OrderController.java
Feat: Order 컨트롤러 수정
Motivation:
- Order Parameter hidden 추가
Modification:
- Order Parameter hidden 추가
=> Feat: Order 컨트롤러 수정

src/main/java/com/gamsung/backend/domain/member/controller/MemberController.java, src/main/java/com/gamsung/backend/domain/order/controller/OrderController.java, src/main/java/com/gamsung/backend/global/config/SwaggerConfig.java, src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java
=> Docs: 멤버 도메인 Swagger 수정

src/main/java/com/gamsung/backend/domain/order/dto/response/OrderResponse.java, src/main/java/com/gamsung/backend/domain/order/dto/response/SoldOutErrorResponse.java, src/main/java/com/gamsung/backend/domain/order/dto/response/SoldOutOrder.java, src/main/java/com/gamsung/backend/domain/order/service/OrderService.java
Feat: Order 반환값 수정
Motivation:
- Order 반환값 수정
Modification:
- Order 반환값 타입 주문일 DATETIME->DATE 수정
- JsonNaming 추가
=> Feat/order 반환값 수정

src/main/java/com/gamsung/backend/domain/order/dto/response/OrderResponse.java
Motivation:
- Order 반환값 수정
Modification:
- Order 반환값 타입 주문일 DATETIME->DATE 수정
- JsonNaming 추가
=> Feat: Order 반환값 수정

src/main/java/com/gamsung/backend/domain/order/controller/OrderController.java, src/main/java/com/gamsung/backend/domain/order/dto/response/FindOrderListResponse.java, src/main/java/com/gamsung/backend/domain/order/repository/OrderRepository.java, src/main/java/com/gamsung/backend/domain/order/service/OrderService.java
Feat: Order 조회 total_page 추가
Motivation:
- 무한스크롤 페이징을 위한 total_page 전달
Modification:
- 무한스크롤 페이징을 위한 total_page 전달 추가
=> Feat/order 조회 total_page 추가

src/main/java/com/gamsung/backend/domain/order/controller/OrderController.java, src/main/java/com/gamsung/backend/domain/order/dto/response/FindOrderListResponse.java, src/main/java/com/gamsung/backend/domain/order/service/OrderService.java
Motivation:
- 무한스크롤 페이징을 위한 total_page 전달
Modification:
- 무한스크롤 페이징을 위한 total_page 전달 추가
=> Feat: Order 조회 total_page 추가

scripts/check_server.sh, scripts/move_server_jar.sh, scripts/server_start.sh, src/main/java/com/gamsung/backend/domain/accommodation/controller/AccommodationController.java, src/main/resources/application-prod.yaml, src/main/resources/logback-spring.xml
=> 배포 서버의 설정 수정

src/test/java/com/gamsung/backend/domain/member/controller/MemberControllerTest.java, src/test/java/com/gamsung/backend/global/jwt/controller/JwtControllerTest.java
=> 멤버 관련 컨트롤러 유닛 테스트 실패 케이스 추가

src/main/java/com/gamsung/backend/global/jwt/JwtProvider.java, src/main/java/com/gamsung/backend/global/jwt/security/JwtAuthenticationProvider.java, src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java, src/test/http/member/refresh.http
=> JWT 액세스 토큰 리프레시 오류 수정

src/main/java/com/gamsung/backend/domain/cart/dto/request/CartEntryRequest.java, src/test/java/com/gamsung/backend/integration/CartIntegrationTest.java
=> Feat : Cart 쪽 테스트 코드 작성

src/main/java/com/gamsung/backend/global/jwt/JwtProvider.java, src/main/java/com/gamsung/backend/global/jwt/repository/JwtRefreshTokenRedisRepository.java, src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java, src/test/java/com/gamsung/backend/global/jwt/JwtProviderTest.java, src/test/java/com/gamsung/backend/global/jwt/repository/JwtRefreshTokenRedisRepositoryTest.java, src/test/java/com/gamsung/backend/global/jwt/service/JwtServiceTest.java
=> JWT 서비스 및 프로바이더 수정

src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java, src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java, src/test/java/com/gamsung/backend/global/jwt/controller/JwtControllerTest.java
=> 리프레시 이후 기존 액세스 토큰 처리방식 추가

src/main/java/com/gamsung/backend/domain/order/dto/request/OrderAccommodationRequest.java, src/test/java/com/gamsung/backend/domain/order/controller/OrderControllerIntegrationTest.java
Motivation:
- Order 도메인 통합테스트
Modification:
- Controller부터 반환까지 도메인 통합 테스트코드 작성
=> Test: Order 통합테스트

src/test/java/com/gamsung/backend/domain/accomodation/controller/AccommodationControllerTest.java
=> Fix: 타입 변환으로 인한 테스트 코드 에러 해결
